---
-
  hosts: all
  become: true
  tasks:
    - name: Copying Public SSH Key
      copy:
        src: id_rsa.pub
        dest: /home/admin/.ssh/id_rsa.pub
        owner: admin
        group: admin
        mode: 0600
    # - name: debug
    #   debug:
    #     msg: "{{ ADMIN_USERNAME }}"
      
    # - name: Create user "{{ item.1 }}"
    #   user:
    #     name: "{{ item.1 }}"
    #     state: present
    #     comment: "{{ item.1 | title }} {{ item.0 }}"
    #   loop: "{{ users | subelements('members') }}"
...