---
-
  hosts: all

  tasks:
    - name: Create user
      user: 
        name: "{{ new_user }}"
        password: "{{ new_password }}"
        state: present
      register: results
    # - name: debug
    #   debug:
    #     msg: "{{ ADMIN_USERNAME }}"
      
    # - name: Create user "{{ item.1 }}"
    #   user:
    #     name: "{{ item.1 }}"
    #     state: present
    #     comment: "{{ item.1 | title }} {{ item.0 }}"
    #   loop: "{{ users | subelements('members') }}"
...